### PR TITLE
Removing tvOS related 

### PR DESCRIPTION
**Pull request by charlyliu**
It also re-removes the Result source file

### CODE REVIEW

**Comment by davideme** [comment]
This repo now use 'Result', '1.0.2' that support tvOS, can you try to restore 
```git checkout origin/antitypical-Result .travis.yml Alamofire.xcodeproj/project.pbxproj Source/Info-tvOS.plist ```

To see if it compile ?

**Comment by charlyliu** [comment]
ok, will try it

**Comment by charlyliu** [comment]
Seems it works. So probably we don't need to remove the tvOS.

But the Result file is still under the Source folder so when we pod install, it downloads the file.

**Comment by davideme** [comment]
Ok, let have it compile for TVos and the rest of the changes are ok.

**Comment by charlyliu** [comment]
oo, I just realized that tvOS doesn't have a target ... 

So we are not compiling a tvOS library. Do we need it? or we just remove the Result file and that's all

**Comment by davideme** [comment]
A prefer to Keep the lib as close as possible to the Alamofire repo.
By deleting only Source/Result.swift it's fine.

**Comment by charlyliu** [comment]
I will close this PR and open another one just removing the Result file

**Comment by davideme** [comment]
:+1:

**Comment by charlyliu** [comment]
https://github.com/Karumi/Alamofire-Result/pull/7

**Pull request closed without merging**
